[package]
name = "clockpro-cache"
description = "CLOCK-Pro cache replacement policy"
version = "0.1.5"
homepage = "https://github.com/jedisct1/rust-clockpro-cache"
keywords = ["cache"]
license = "MIT"
authors = ["Frank Denis <github@pureftpd.org>"]
categories = ["algorithms", "caching"]

[badges]
travis-ci = { repository = "jedisct1/rust-clockpro-cache" }
appveyor = { repository = "jedisct1/rust-clockpro-cache" }

[dependencies]
clippy = {version = "~0", optional = true}
slab = "~0.3"
bitflags = "~1"
