[package]
name = "clockpro-cache"
description = "CLOCK-Pro cache replacement policy"
version = "0.1.4"
homepage = "https://github.com/jedisct1/rust-clockpro-cache"
keywords = ["cache"]
license = "MIT"
authors = ["Frank Denis <github@pureftpd.org>"]

[dependencies]
slab = "~0.3.0"
bitflags = "~0.7.0"
